spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    hikari:
      username: root
      password: roots
#    username: root
#    password: roots
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true