server:
  port: 8060
spring:
  datasource:
    data-username: root
    data-password: roots
    url: jdbc:mysql://localhost:3306/security_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
  security:
    user:
      name: xjc
      password: xjc


